In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Create NumPy array
Pass a python list to np.array(list)  
np.zeros((5,3)) pass a tuple of integers to shape the array
* Same with np.random.random((2,4))  

np.arange(-3,4)
## Numpy Arrays
* Same data types

In [8]:
ar1 = np.array([[1,2], [3,4]])
ar2 = np.array([[5,6], [7,8]])
ar3 = np.array([[9,10], [11,12]])
threeDimArr = np.array([ar1,ar2,ar3])
print(threeDimArr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Vector - array of 1 dimension  
Matrix = 2 dimensions  
Tenson = 3+ dimensions  
Rows = 1st dimension  
Columns = 2nd dimension  
### Array attributes & methods
* arr.shape()
* arr.reshape()
* arr.flatten()

## Numpy Datatypes  
np.int64  
np.int32  
np.float64  
np.float32  
### Array data type
arr.dtype