In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Create NumPy array
Pass a python list to np.array(list)  
np.zeros((5,3)) pass a tuple of integers to shape the array
* Same with np.random.random((2,4))  

np.arange(-3,4)
## Numpy Arrays
* Same data types

In [2]:
ar1 = np.array([[1,2], [3,4]])
ar2 = np.array([[5,6], [7,8]])
ar3 = np.array([[9,10], [11,12]])
threeDimArr = np.array([ar1,ar2,ar3])
print(threeDimArr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Vector - array of 1 dimension  
Matrix = 2 dimensions  
Tenson = 3+ dimensions  
Rows = 1st dimension  
Columns = 2nd dimension  
### Array attributes & methods
* arr.shape()
* arr.reshape()
* arr.flatten()

## Numpy Datatypes  
np.int64  
np.int32  
np.float64  
np.float32  
### Array data type
arr.dtype

## Indexing and slicing arrays  
### Sorting
np.sort(array) by rows or columns

## Filtering  
### Masks and fancy indexing
Index the array using the mask to filter for specific values
### np.where()
Returns array of **indices** of elements that meet the condition  
Indices can be used to update an array

## Adding and removing data
### np.concatenate((tuple))
* axis argument for columns or rows  
* Needs to have compatible shapes on the axis where you're trying to concatenate
* Need dimension compatibility  
use arr.reshape()
* Can't add new dimensions  

### np.delete(array, slice or array of indices, axis)
Outputs a flattened array when axis is not specified

## Summarizing data
* .sum(axis)
* .min(axis) or .max(axis)
* .mean()  
Optional keepdims=Boolean to keep the dimensions  
* .cumsum()

## Vectorized operations
Outsource to C  
array + scalar
### Boolean masks
An array is a scalar (vectorized syntax)
### np.vectorize(python function)
Vectorize a python function into a numpy function  
**Example**  
vectorized_upper = np.vectorize(**str**.upper)

## Broadcasting
Math operations between arrays of different shapes
### Compatibility rules
1. Compare array dimensions from right to left  
Compatible when one has a length of 1 or they are of equal lengths
1. All dimension sets must be compatible
1. Two arrays don't need the same number of dimensions to be broadcastable  
**You can reshape the arrays to make the trailing dimension compatible**

## Saving and loading arrays
### Loading
with open("logo.npy", "rb") as f:  
&nbsp;&nbsp; logo_rgb_array = np.load(f)  
plt.imshow(logo_rgb_array)  
plt.show()
### Saving
with open("new_logo.npy", "wb") as f:  
&nbsp;&nbsp; np.save(f,new_logo_array)